package GUI;

import Rechner.Verbrenner;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

public class GUIMain {
    private JButton fahre1KmButton;
    private JSpinner aKilometerstandTextField;
    public JPanel panelMain;
    private JButton fahre25KmButton;
    private JSpinner aTankinhaltTextField;
    private JLabel tankinhaltLabel;
    private JLabel kilometerstandLabel;
    private JButton tanke1LButton;
    private JButton tanke25LButton;
    private JSpinner aFahrtkostensummeTextField;
    private JLabel summeFahrtkostenLabel;
    Verbrenner verbrenner1 = new Verbrenner(10, 2, 20);

    public GUIMain() {
        aTankinhaltTextField.setValue(verbrenner1.getTankinhalt());

        fahre1KmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verbrenner1.fahre(1);
                System.out.println("Kilometerstand geändert auf " + verbrenner1.getKilometerstand());
                aKilometerstandTextField.setValue(verbrenner1.getKilometerstand());
                aTankinhaltTextField.setValue(verbrenner1.getTankinhalt());
                aFahrtkostensummeTextField.setValue(verbrenner1.getFahrtkosten());
            }
        });
        fahre25KmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verbrenner1.fahre(25);
                System.out.println("Kilometerstand geändert auf " + verbrenner1.getKilometerstand());
                aKilometerstandTextField.setValue(verbrenner1.getKilometerstand());
                aTankinhaltTextField.setValue(verbrenner1.getTankinhalt());
                aFahrtkostensummeTextField.setValue(verbrenner1.getFahrtkosten());
            }
        });
        tanke1LButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verbrenner1.tanken(1);
                System.out.println("Tank aufgefüllt auf " + verbrenner1.getTankinhalt());
                aTankinhaltTextField.setValue(verbrenner1.getTankinhalt());
            }
        });
        tanke25LButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verbrenner1.tanken(25);
                System.out.println("Tank aufgefüllt auf " + verbrenner1.getTankinhalt());
                aTankinhaltTextField.setValue(verbrenner1.getTankinhalt());
            }
        });

        aKilometerstandTextField.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {

            }
        });
        aTankinhaltTextField.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                verbrenner1.setTankinhalt((Double) aTankinhaltTextField.getValue());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridBagLayout());
        kilometerstandLabel = new JLabel();
        kilometerstandLabel.setText("Kilometerstand");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panelMain.add(kilometerstandLabel, gbc);
        fahre1KmButton = new JButton();
        fahre1KmButton.setText("fahre 1 km");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(fahre1KmButton, gbc);
        fahre25KmButton = new JButton();
        fahre25KmButton.setText("fahre 25 km");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(fahre25KmButton, gbc);
        aKilometerstandTextField = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(aKilometerstandTextField, gbc);
        aTankinhaltTextField = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(aTankinhaltTextField, gbc);
        tankinhaltLabel = new JLabel();
        tankinhaltLabel.setText("Tankinhalt");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panelMain.add(tankinhaltLabel, gbc);
        tanke1LButton = new JButton();
        tanke1LButton.setText("tanke 1 L");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(tanke1LButton, gbc);
        tanke25LButton = new JButton();
        tanke25LButton.setText("tanke 25 L");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(tanke25LButton, gbc);
        summeFahrtkostenLabel = new JLabel();
        summeFahrtkostenLabel.setText("Summe Fahrtkosten");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        panelMain.add(summeFahrtkostenLabel, gbc);
        aFahrtkostensummeTextField = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(aFahrtkostensummeTextField, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer7, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
